# vim: set nospell:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # plugin for async
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # show :help in japanese
repo = 'vim-jp/vimdoc-ja'

[[plugins]] # provides syntax/indent for multiple
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = []
'''

#[[plugins]] # plugin for formatexpr
#repo = 'vim-jp/autofmt'

#[[plugins]]
#repo = 'rcmdnk/vim-markdown'

[[plugins]] # detect the filetype of the place of cursor
repo = 'Shougo/context_filetype.vim'

[[plugins]] # file type switching according to the cursor context
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']


[[plugins]] # plugin for colorscheme iceberg
repo = 'cocopon/iceberg.vim'
hook_add = '''
au MyAutoCmd VimEnter * nested colorscheme iceberg
'''

[[plugins]] # plugin for lightline
repo = 'itchyny/lightline.vim'
hook_add ='''
call Source_rc("plugin-settings/lightline.vim")
'''

[[plugins]] # plugin for quickrun
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {}
let g:quickrun_config.cpp = { 'command': 'g++','cmdopt': '-std=c++14'}
'''

[[plugins]] # plugin for denite
repo = 'Shougo/denite.nvim'
hook_add = '''
call Source_rc("plugin-settings/denite.vim")
'''

[[plugins]] # plugin for multi cursors
repo = 'terryma/vim-multiple-cursors'

# for deoplete
[[plugins]] # plugin for deoplete on vim
repo = 'roxma/nvim-yarp'
if = '!has("nvim")'

# for deoplete
[[plugins]] # plugin for deoplete on vim
repo = 'roxma/vim-hug-neovim-rpc'
if = '!has("nvim")'


[[plugins]] # accelerated jk
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>'}
hook_add = '''
nmap <silent>j <Plug>(accelerated_jk_gj)
nmap <silent>k <Plug>(accelerated_jk_gk)
'''

[[plugins]] # trailing whitespace
repo = 'bronson/vim-trailing-whitespace'
hook_add ='''
let g:extra_whitespace_ignored_filetypes = ['unite', 'fzf']
'''

[[plugins]] # indent line
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_char = '¦'
'''

[[plugins]] # fugitive
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'


#[[plugins]]
#repo = 'junegunn/fzf'
#build = './install --bin'
#merged = '0'
#
#[[plugins]]
#repo = 'junegunn/fzf.vim'
#depends = 'fzf'
#hook_add = '''
#command! -bang -nargs=* Rg
#\ call fzf#vim#grep(
#    \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
#    \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))
#'''


[[plugins]]
repo = 'preservim/nerdcommenter'
hook_add = '''
let g:NERDSpaceDelims = 1
let g:NERDCommentEmptyLines = 1
let g:NERDTrimTrailingWhitespace = 1
" let g:NERDCreateDefaultMappings = 0
'''
[[plugins]]
repo = 'jiangmiao/auto-pairs'


[[plugins]]
repo = 'thinca/vim-scouter'
